version: '3.8'
services:
    website:
        #build:
            #context: github.com/loaker-labs/website.git
            #dockerfile: Dockerfile
            #ssh:["default"]
        build: https://github.com/loaker-labs/website.git
        container_name: "loaker-website"
        #privileged: true
        image: loaker-website:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/live/loaker.ch:/app/dist/server
            #- /etc/letsencrypt/live/loaker.ch/privkey.pem:/app/dist/server/privkey.pem
            #- /etc/letsencrypt/live/loaker.ch/fullchain.pem:/app/dist/server/fullchain.pem
        #environment:
            #- TZ=Europe/Paris
            #- MYSQL_DATABASE=oai_db
            #- MYSQL_USER=test
            #- MYSQL_PASSWORD=test
            #- MYSQL_ROOT_PASSWORD=linux
        #depends_on:
          #- loaker-database
        healthcheck:
            test: ["CMD", "curl -Is --max-time 4 https://loaker.ch"]
            interval: 10s
            timeout: 5s
            retries: 30
        #networks:
            #public_net:
                #ipv4_address: 192.168.71.131